# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [2]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [3]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [4]:
np.__version__

'2.0.2'

In [5]:
np.show_config()

Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.11
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/4d/0gnh84wj53j7wyk695q0tc_80000gn/T/build-env-kq4k

#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
null_vector.size * null_vector.itemsize

80

In [8]:
null_vector.nbytes

80

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [9]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
null_vector_6 = np.zeros(10)
null_vector_6[4] = 1
null_vector_6

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
vec_10_49 = np.arange(10,50)
vec_10_49

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [12]:
vec_10_49_rev = vec_10_49[::-1]
vec_10_49_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
mat_33_08 = np.zeros((3,3))

for i in range(mat_33_08.shape[0]):
    for j in range(mat_33_08.shape[1]):
        mat_33_08[i,j] = (i * mat_33_08.shape[0])+j
mat_33_08

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [14]:
non_zero_ids = np.nonzero(np.array([1,2,0,0,4,0]))
non_zero_ids

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.random((3,3))

array([[6.62923678e-01, 8.37106551e-02, 8.15463900e-01],
       [2.46905702e-04, 3.77948321e-01, 8.25716867e-01],
       [4.08740415e-01, 2.53640581e-01, 8.64423064e-01]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [17]:
rand_1010 = np.random.random((10,10))
min = rand_1010.min()
max = rand_1010.max()
min, max

(np.float64(0.005350888444423663), np.float64(0.9986604969681359))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [18]:
rand_30 = np.random.random(30)
mean = rand_30.mean()
rand_30, mean

(array([0.56287229, 0.89803851, 0.20639218, 0.22437663, 0.88785664,
        0.10433104, 0.81978642, 0.80185767, 0.608598  , 0.79740496,
        0.00529453, 0.38537835, 0.76902416, 0.85243059, 0.82389173,
        0.73022236, 0.79468224, 0.74396529, 0.93835992, 0.63394931,
        0.5383801 , 0.39933016, 0.59322786, 0.68255897, 0.1585281 ,
        0.45081613, 0.25289135, 0.86260432, 0.94992276, 0.48525228]),
 np.float64(0.5987408284067056))

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [19]:
zero_in = np.ones((5,5))
zero_in[1:-1, 1:-1]=0
zero_in

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [20]:
existing_arr = np.ones((5,5))
print(existing_arr)
border = np.zeros((existing_arr.shape[0] + 2, existing_arr.shape[1] + 2))
border[1:-1, 1:-1] = existing_arr
existing_arr = border
existing_arr

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [21]:
np.nan,0,0,np.nan,1,0

(nan, 0, 0, nan, 1, 0)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [22]:
below_diagonal = np.zeros((5,5))
below_diagonal += np.diag(np.arange(1,5),k=-1)
below_diagonal

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [23]:
checkerboard = np.zeros((8,8))
checkerboard[::2,::2] = 1
checkerboard[1::2,1::2] = 1
checkerboard

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [24]:
shape_678 = np.zeros((6,7,8))
np.unravel_index(99, shape_678.shape)

(np.int64(1), np.int64(5), np.int64(3))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [25]:
np.tile(np.array([[0,1],[1,0]]), (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [26]:
rnd_mat_5 = np.random.random((5,5))
rnd_mat_5 = (rnd_mat_5 - rnd_mat_5.mean()) / rnd_mat_5.std()
rnd_mat_5.mean(), rnd_mat_5.std()

(np.float64(-1.2434497875801754e-16), np.float64(0.9999999999999999))

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [27]:
rgba_type = np.dtype([
    ('R',np.ubyte),
    ('G',np.ubyte),
    ('B',np.ubyte),
    ('A',np.ubyte)
])
rgba_type

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [28]:
np.random.randint(1,10,(5,3)) @ np.random.randint(1,10,(3,2))

array([[ 70, 103],
       [ 78, 117],
       [ 45, 110],
       [ 75,  98],
       [ 76, 109]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [29]:
d1 = np.arange(10)
d1[3:9] = ~d1[3:9] + 1
d1

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [30]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [31]:
1,1,1,1,1,0

(1, 1, 1, 1, 1, 0)

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [32]:
np.nan, 0, 0.

(nan, 0, 0.0)

#### 29. How to round away from zero a float array ? (★☆☆)

In [33]:
rand_arr = (np.random.random(10) - 0.5) * 10
print(rand_arr)
neg_id = np.where(rand_arr < 0)
pos_id = np.where(rand_arr > 0)
rand_arr[pos_id] = np.ceil(rand_arr[pos_id])
rand_arr[neg_id] = np.ceil(rand_arr[neg_id])
rand_arr

[-4.86194947  2.23791938 -3.57976895  3.86761392 -4.00587257 -4.17561057
 -2.21932671 -0.20365887  1.61130661 -3.44547466]


array([-4.,  3., -3.,  4., -4., -4., -2., -0.,  2., -3.])

#### 30. How to find common values between two arrays? (★☆☆)

In [34]:
first = np.random.randint(0,10,5)
second = np.random.randint(0,10,5)
print(first, second)
np.intersect1d(first,second)

[9 8 6 1 4] [4 3 6 6 3]


array([4, 6])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [35]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [36]:
0

0

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [37]:
today = np.datetime64('today', 'D')

yesterday = today - np.timedelta64(1, 'D')

tomorrow = today + np.timedelta64(1, 'D')
today, yesterday, tomorrow

(np.datetime64('2025-04-23'),
 np.datetime64('2025-04-22'),
 np.datetime64('2025-04-24'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [38]:
np.arange('2016-06', '2016-07', dtype='datetime64[D]')

array(['2016-06-01', '2016-06-02', '2016-06-03', '2016-06-04',
       '2016-06-05', '2016-06-06', '2016-06-07', '2016-06-08',
       '2016-06-09', '2016-06-10', '2016-06-11', '2016-06-12',
       '2016-06-13', '2016-06-14', '2016-06-15', '2016-06-16',
       '2016-06-17', '2016-06-18', '2016-06-19', '2016-06-20',
       '2016-06-21', '2016-06-22', '2016-06-23', '2016-06-24',
       '2016-06-25', '2016-06-26', '2016-06-27', '2016-06-28',
       '2016-06-29', '2016-06-30'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [39]:
A = np.random.randint(0,10,5)
B = np.random.randint(0,10,5)
np.add(A,B,out=B)
np.negative(A,out=A)
np.divide(A,2,out=A, casting='unsafe')
np.multiply(A,B, out=A)
A

array([-10, -52, -12, -45, -24])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [40]:
np.tile(np.arange(5), (5,1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [41]:
np.linspace(0,1,11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [42]:
np.sort(np.random.rand(10))

array([0.01431965, 0.08816855, 0.47341021, 0.58227219, 0.68213685,
       0.69232734, 0.76943803, 0.78302173, 0.88841729, 0.92694391])

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [43]:
A = np.random.randint(0,2,1)
B = np.random.randint(0,2,1)
print(A,B)
np.all(A==B)

[0] [1]


np.False_

#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
arr = np.zeros(3)
arr.flags.writeable = False
#arr[0] = 1 - error

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
A = np.random.randint(1,5,(10,2))
print(A)

r = np.sqrt((A[:,0]**2 + A[:,1]**2))
t = np.arctan2(A[:,1], A[:,0])

A[:,0] = r
A[:,1] = t

A

[[3 1]
 [1 3]
 [4 3]
 [1 1]
 [4 1]
 [3 1]
 [4 2]
 [3 3]
 [3 1]
 [1 4]]


array([[3, 0],
       [3, 1],
       [5, 0],
       [1, 0],
       [4, 0],
       [3, 0],
       [4, 0],
       [4, 0],
       [3, 0],
       [4, 1]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
rand = np.random.rand(10)
print(rand)
rand[rand.argmax()] = 0
rand

[0.24439237 0.89474089 0.82606335 0.86562044 0.53186766 0.2126383
 0.82859767 0.53714895 0.37079173 0.26874658]


array([0.24439237, 0.        , 0.82606335, 0.86562044, 0.53186766,
       0.2126383 , 0.82859767, 0.53714895, 0.37079173, 0.26874658])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [48]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [49]:
np.set_printoptions(threshold=float("inf"))

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [50]:
vector = np.random.randint(0,10,10)
scalar = 5
print(vector)
vector[np.argmin(np.abs(vector - scalar))]

[6 5 8 6 3 8 4 7 4 3]


np.int64(5)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [51]:
np.zeros((3,1), dtype=[('position', [('x', float),('y', float)]),('color', [('r', float),('g', float),('b', float)])])

array([[((0., 0.), (0., 0., 0.))],
       [((0., 0.), (0., 0., 0.))],
       [((0., 0.), (0., 0., 0.))]],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [52]:
rand = np.random.randint(0,100, (100,2))
X = rand[:,0].reshape(1,-1)
Y = rand[:,1].reshape(1,-1)
D = np.sqrt((X - X.T)**2 + (Y - Y.T)**2)
D

array([[  0.        ,  48.33218389, 114.69088891,  16.2788206 ,
        101.23734489,  72.9177619 ,  90.02221948,  24.08318916,
         79.92496481,  58.24946352,  17.08800749,   7.28010989,
         98.41239759,  49.81967483,  75.18643495,  43.829214  ,
         90.66973034,  45.27692569,  77.38862966,  86.64871609,
        115.12167476,  81.68843247,  19.10497317,  52.61178575,
         25.8069758 ,  99.12618221,  85.90692638,  72.09022125,
         38.32753579,  46.09772229, 116.82465493,  89.55445271,
        107.80074211,  28.23118843,  87.09190548,  82.09750301,
         66.48308055,  97.86214794,  28.01785145, 102.78618584,
         55.02726597,  91.54780172,  86.21484791,  31.57530681,
         77.1621669 ,  74.81310046,  66.21933252, 124.48293056,
        121.91800523,  30.8058436 ,  89.56003573,  10.44030651,
         80.80222769,  28.0713377 ,  65.80273551,  51.10772936,
        100.12492197, 111.77208954, 108.97706181,  64.19501538,
         62.80127387,  86.76981042,  57.

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [53]:
fl_ar = (np.random.rand(5) * 100).astype(np.float32)
fl_ar = fl_ar.astype(np.int32)
fl_ar

array([67, 36, 43, 51, 80], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [54]:
from io import StringIO
file_str = StringIO("""
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
""")
np.genfromtxt(file_str, delimiter=',', dtype=int)

array([[ 1,  2,  3,  4,  5],
       [ 6, -1, -1,  7,  8],
       [-1, -1,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [55]:
for i, x in np.ndenumerate([1,2,3]):
    print(i,x)

(0,) 1
(1,) 2
(2,) 3


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [56]:
X, Y = np.meshgrid(np.linspace(1,10,10), np.linspace(1,10,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[3.67879441e-01 8.20849986e-02 6.73794700e-03 2.03468369e-04
  2.26032941e-06 9.23744966e-09 1.38879439e-11 7.68120469e-15
  1.56288219e-18 1.16984592e-22]
 [8.20849986e-02 1.83156389e-02 1.50343919e-03 4.53999298e-05
  5.04347663e-07 2.06115362e-09 3.09881914e-12 1.71390843e-15
  3.48726153e-19 2.61027907e-23]
 [6.73794700e-03 1.50343919e-03 1.23409804e-04 3.72665317e-06
  4.13993772e-08 1.69189792e-10 2.54366565e-13 1.40686171e-16
  2.86251858e-20 2.14264754e-24]
 [2.03468369e-04 4.53999298e-05 3.72665317e-06 1.12535175e-07
  1.25015287e-09 5.10908903e-12 7.68120469e-15 4.24835426e-18
  8.64405711e-22 6.47023493e-26]
 [2.26032941e-06 5.04347663e-07 4.13993772e-08 1.25015287e-09
  1.38879439e-11 5.67568523e-14 8.53304763e-17 4.71949527e-20
  9.60268005e-24 7.18778174e-28]
 [9.23744966e-09 2.06115362e-09 1.69189792e-10 5.10908903e-12
  5.67568523e-14 2.31952283e-16 3.48726153e-19 1.92874985e-22
  3.92439586e-26 2.93748211e-30]
 [1.38879439e-11 3.09881914e-12 2.54366565e-13 7.68120469e

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [57]:
p_elem = (np.random.rand(100) * 100).astype(int)

arr = np.zeros((10,10))

xs = np.random.choice(10, 10, replace=False)
ys = np.random.choice(10, 10, replace=False)
x, y = np.meshgrid(xs,ys)
x = x.reshape(-1)
y = y.reshape(-1)

for i in range(len(p_elem)):
    arr[x[i], y[i]] = p_elem[i]

arr

array([[99., 58.,  3., 50., 77., 94., 69., 18., 47., 40.],
       [52.,  0., 40., 52., 50., 95., 21., 94., 84., 54.],
       [80., 44., 62., 51., 46., 67., 61., 89.,  5., 21.],
       [60., 17.,  0.,  3., 39., 77.,  6., 46., 76., 74.],
       [88., 99., 28., 45.,  4., 94., 27., 77., 73.,  5.],
       [95., 70., 64., 52., 44.,  0.,  7., 73., 43., 13.],
       [58., 24., 92., 95., 24., 22., 36., 63., 80.,  7.],
       [26., 22., 66., 32., 29., 73., 96., 26., 17., 63.],
       [75., 65., 46., 35., 10., 53., 75.,  0., 71., 97.],
       [71., 96.,  2., 66., 45., 35., 62., 62., 75., 94.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [63]:
mat = np.random.randint(1,10,(4,4))
print(mat)

means = np.mean(mat, axis = 1, keepdims=True)
print(means)

mat_mean = np.subtract(mat, means)
mat_mean

[[8 7 9 8]
 [4 6 3 6]
 [3 3 3 1]
 [7 5 9 7]]
[[8.  ]
 [4.75]
 [2.5 ]
 [7.  ]]


array([[ 0.  , -1.  ,  1.  ,  0.  ],
       [-0.75,  1.25, -1.75,  1.25],
       [ 0.5 ,  0.5 ,  0.5 , -1.5 ],
       [ 0.  , -2.  ,  2.  ,  0.  ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [67]:
mat = np.random.randint(1,10,(4,4))
print(mat)

n = 2

mat[mat[:,n].argsort()]

[[2 9 4 5]
 [4 5 1 2]
 [5 9 4 5]
 [9 3 5 5]]


array([[4, 5, 1, 2],
       [2, 9, 4, 5],
       [5, 9, 4, 5],
       [9, 3, 5, 5]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [81]:
mat = np.random.rand(4,4)
mat[:, 1] = np.nan

print(mat)

isna = np.isnan(mat)
print(isna)

sum = np.sum(isna, axis=0)
print(sum)

result = (np.sum(sum == mat.shape[1]) > 0)
result


[[0.54892347        nan 0.28885275 0.0806971 ]
 [0.76027568        nan 0.55459879 0.762784  ]
 [0.4699028         nan 0.02681919 0.98999172]
 [0.40439288        nan 0.50277631 0.17038237]]
[[False  True False False]
 [False  True False False]
 [False  True False False]
 [False  True False False]]
[0 4 0 0]


np.True_

In [83]:
print(isna.all(axis=0))

[False  True False False]


#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)